services:
  social_nest_backend:
    build: ./socialmediaBackend
    image: shubham09anand/social_nest_backend:latest
    container_name: social_nest_backend
    ports:
      - '8080:8080'
    networks:
      - socialnestnetwork
    depends_on:
      - mongo

  social_nest_frontend:
    build: ./socialmedia
    image: shubham09anand/social_nest_frontend:latest
    container_name: social_nest_frontend
    ports:
      - '3000:3000'
    networks:
      - socialnestnetwork
    depends_on:
      - social_nest_backend

  mongo:
    image: mongo:7.0
    container_name: mongo_container
    ports:
      - '27017:27017'
    networks:
      - socialnestnetwork
    volumes:
      - F:/Docker data:/data/db

networks:
  socialnestnetwork:
    driver: bridge

volumes:
  mongo_data:
